version: "3"

tasks:
  mod:
    desc: updates the go modules
    cmds:
      - go mod download

  test:
    desc: runs the tests
    deps:  [mod]
    cmds:
      - go test -skip TestIntegration  -v ./... -race

  benchmark:
    desc: runs the benchmarks
    deps:  [mod]
    cmds:
      - go test -run=^$ -bench=. -benchmem -v ./... -race

  integration_test:
    desc: runs the integration tests
    deps:  [mod]
    cmds:
      - go test -v test/integration_test.go -race

  run:
    desc: starts the API
    deps:  [mod]
    cmds:
      - go run cmd/main.go

  run_persistence:
    desc: starts the API with persistence enabled
    deps:  [mod]
    env:
      PERSISTENCE_ENABLED: true
      DB_PATH: .db
      # VERBOSE: debug
    cmds:
      - go run cmd/main.go

  docker:
    desc: start the docker-compose
    cmds:
      - docker compose up --build -d